ITEM_GROUPS = {
	["Playable Character"] = {"jazz_unlock", "spaz_unlock", "lori_unlock"},
	["The Secret Files Content"] = {"lori_unlock", "easter_bunny_unlock", "spring_chickens_unlock", "scrambled_eggs_unlock", "ghostly_antics_unlock", "skeletons_turf_unlock", "graveyard_shift_unlock", "turtle_town_unlock", "suburbia_commando_unlock", "urban_brawl_unlock", "the_secret_files_progressive_level_unlock"},
	["Christmas Chronicles Content"] = {"lori_unlock", "snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock", "christmas_chronicles_progressive_level_unlock"},
	["Basic Movement Ability"] = {"double_jump_unlock", "copter_ears_unlock", "uppercut_unlock", "sidekick_unlock", "buttstomp_unlock", "swimming_unlock", "vine_traversal", "hook_traversal"},
	["Level Movement Ability"] = {"wildcard_destructible_scenery", "bouncer_destructible_scenery", "rf_missile_destructible_scenery", "toaster_destructible_scenery", "tnt_destructible_scenery", "speed_destructible_scenery", "special_move_destructible_scenery"},
	["Weapon Unlock"] = {"blaster_permit", "bouncer_permit", "freezer_permit", "seeker_permit", "rf_missile_permit", "toaster_permit", "tnt_permit", "pepper_spray_permit", "electro_blaster_permit"},
	["Level Unlock"] = {"rabbit_in_training_unlock", "dungeon_dilemma_unlock", "knight_cap_unlock", "tossed_salad_unlock", "carrot_juice_unlock", "weirder_science_unlock", "loose_screws_unlock", "formerly_a_prince_progressive_level_unlock", "victorian_secret_unlock", "colonial_chaos_unlock", "purple_haze_maze_unlock", "funky_grooveathon_unlock", "beach_bunny_bingo_unlock", "marinated_rabbit_unlock", "jazz_in_time_progressive_level_unlock", "a_diamondus_forever_unlock", "fourteen_carrot_unlock", "electric_boogaloo_unlock", "voltage_village_unlock", "medieval_kineval_unlock", "hare_scare_unlock", "gargoyles_lair_unlock", "flashback_progressive_level_unlock", "thriller_gorilla_unlock", "jungle_jump_unlock", "a_cold_day_in_heck_unlock", "rabbit_roast_unlock", "burnin_biscuits_unlock", "bad_pitt_unlock", "funky_monkeys_progressive_level_unlock", "darn_ratz_unlock", "retro_rabbit_unlock", "frog_stomp_unlock", "shareware_demo_progressive_level_unlock", "easter_bunny_unlock", "spring_chickens_unlock", "scrambled_eggs_unlock", "ghostly_antics_unlock", "skeletons_turf_unlock", "graveyard_shift_unlock", "turtle_town_unlock", "suburbia_commando_unlock", "urban_brawl_unlock", "the_secret_files_progressive_level_unlock", "snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock", "christmas_chronicles_progressive_level_unlock"},
	["Individual Level Unlocks"] = {"rabbit_in_training_unlock", "dungeon_dilemma_unlock", "knight_cap_unlock", "tossed_salad_unlock", "carrot_juice_unlock", "weirder_science_unlock", "loose_screws_unlock", "victorian_secret_unlock", "colonial_chaos_unlock", "purple_haze_maze_unlock", "funky_grooveathon_unlock", "beach_bunny_bingo_unlock", "marinated_rabbit_unlock", "a_diamondus_forever_unlock", "fourteen_carrot_unlock", "electric_boogaloo_unlock", "voltage_village_unlock", "medieval_kineval_unlock", "hare_scare_unlock", "gargoyles_lair_unlock", "thriller_gorilla_unlock", "jungle_jump_unlock", "a_cold_day_in_heck_unlock", "rabbit_roast_unlock", "burnin_biscuits_unlock", "bad_pitt_unlock", "darn_ratz_unlock", "retro_rabbit_unlock", "frog_stomp_unlock", "easter_bunny_unlock", "spring_chickens_unlock", "scrambled_eggs_unlock", "ghostly_antics_unlock", "skeletons_turf_unlock", "graveyard_shift_unlock", "turtle_town_unlock", "suburbia_commando_unlock", "urban_brawl_unlock", "snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock"},
	["Episode: Formerly a Prince"] = {"rabbit_in_training_unlock", "dungeon_dilemma_unlock", "knight_cap_unlock", "tossed_salad_unlock", "carrot_juice_unlock", "weirder_science_unlock", "loose_screws_unlock", "formerly_a_prince_progressive_level_unlock"},
	["Starting Levels"] = {"rabbit_in_training_unlock", "dungeon_dilemma_unlock", "formerly_a_prince_progressive_level_unlock", "victorian_secret_unlock", "jazz_in_time_progressive_level_unlock", "a_diamondus_forever_unlock", "flashback_progressive_level_unlock", "thriller_gorilla_unlock", "funky_monkeys_progressive_level_unlock", "darn_ratz_unlock", "shareware_demo_progressive_level_unlock", "easter_bunny_unlock", "the_secret_files_progressive_level_unlock", "snow_bunnies_unlock", "christmas_chronicles_progressive_level_unlock"},
	["Safe Free Select Starting Levels"] = {"rabbit_in_training_unlock", "dungeon_dilemma_unlock", "knight_cap_unlock", "tossed_salad_unlock", "carrot_juice_unlock", "victorian_secret_unlock", "funky_grooveathon_unlock", "beach_bunny_bingo_unlock", "marinated_rabbit_unlock", "fourteen_carrot_unlock", "electric_boogaloo_unlock", "thriller_gorilla_unlock", "a_cold_day_in_heck_unlock", "darn_ratz_unlock", "easter_bunny_unlock", "spring_chickens_unlock", "ghostly_antics_unlock", "skeletons_turf_unlock", "turtle_town_unlock", "urban_brawl_unlock", "snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock"},
	["Progressive Level Unlocks"] = {"formerly_a_prince_progressive_level_unlock", "jazz_in_time_progressive_level_unlock", "flashback_progressive_level_unlock", "funky_monkeys_progressive_level_unlock", "shareware_demo_progressive_level_unlock", "the_secret_files_progressive_level_unlock", "christmas_chronicles_progressive_level_unlock"},
	["Episode: Jazz in Time"] = {"victorian_secret_unlock", "colonial_chaos_unlock", "purple_haze_maze_unlock", "funky_grooveathon_unlock", "beach_bunny_bingo_unlock", "marinated_rabbit_unlock", "jazz_in_time_progressive_level_unlock"},
	["Episode: Flashback"] = {"a_diamondus_forever_unlock", "fourteen_carrot_unlock", "electric_boogaloo_unlock", "voltage_village_unlock", "medieval_kineval_unlock", "hare_scare_unlock", "gargoyles_lair_unlock", "flashback_progressive_level_unlock"},
	["Episode: Funky Monkeys"] = {"thriller_gorilla_unlock", "jungle_jump_unlock", "a_cold_day_in_heck_unlock", "rabbit_roast_unlock", "burnin_biscuits_unlock", "bad_pitt_unlock", "funky_monkeys_progressive_level_unlock"},
	["Episode: Shareware Demo"] = {"darn_ratz_unlock", "retro_rabbit_unlock", "frog_stomp_unlock", "shareware_demo_progressive_level_unlock"},
	["Episode: The Secret Files"] = {"easter_bunny_unlock", "spring_chickens_unlock", "scrambled_eggs_unlock", "ghostly_antics_unlock", "skeletons_turf_unlock", "graveyard_shift_unlock", "turtle_town_unlock", "suburbia_commando_unlock", "urban_brawl_unlock", "the_secret_files_progressive_level_unlock"},
	["Episode: Christmas Chronicles"] = {"snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock", "christmas_chronicles_progressive_level_unlock"},
	["Holiday Hare Content"] = {"snow_bunnies_unlock", "dashing_thru_the_snow.._unlock", "tinsel_town_unlock", "christmas_chronicles_progressive_level_unlock"}
}


ITEM_VALUES = {

}


STAGE_MAPPINGS = {

}
